name: Uniffi Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_xcframework:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make prepare-apple
          cd hello
          make all

      - name: "Upload xcframework"
        uses: actions/upload-artifact@v2
        with:
          name: HelloFFI.xcframework
          path: hello/target/HelloFFI.xcframework
          retention-days: 7

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
          # Reference: https://github.com/mozilla/rust-android-gradle/blob/master/.github/workflows/check.yml
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
      - uses: actions-rs/toolchain@v1
        # Reference: https://github.com/rust-windowing/android-ndk-rs/blob/master/.github/workflows/rust.yml
        with:
          toolchain: stable
          override: true
          target: aarch64-linux-android
      - name: "More dependencies"
        run: |
          make prepare-android
      - name: "Build Android library"
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cd hello/platforms/android/UniffiRustExample
          ./gradlew cargoBuild --info
