name: Uniffi Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_xcframework:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make prepare-apple
          cd hello
          make all

      - name: "Upload xcframework"
        uses: actions/upload-artifact@v2
        with:
          name: HelloFFI.xcframework
          path: hello/target/HelloFFI.xcframework
          retention-days: 7

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
      - name: "Build Android library"
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cd hello/platforms/android/UniffiRustExample
          ./gradlew cargoBuild --info
